name = "Address Validator++  Checkout UI"
uid = "720aceaa-89e9-38ae-eb4f-2de1228dfab128dab746"
type = "ui_extension"
surface = "checkout"
api_version = "2025-01"
extension_points = [
  { target = "purchase.checkout.delivery-address.render-after", module = "./src/index.jsx" }
]

capabilities = { block_progress = true, network_access = true }

# Notes:
# - The extension will call our backend using a short-lived session token (getSessionToken) later.
# - Do NOT include secrets in this bundle.
