# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5157c62e833750cbbe886fa1f9995997"
name = "address-validator++"
application_url = "https://substantial-from-sensor-vast.trycloudflare.com"
embedded = true
handle = "address-validator-36"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customers,write_customers,read_orders"

[auth]
redirect_urls = ["https://substantial-from-sensor-vast.trycloudflare.com/auth/callback", "https://substantial-from-sensor-vast.trycloudflare.com/auth/shopify/callback", "https://substantial-from-sensor-vast.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
